# Generated by Django 4.2.1 on 2023-06-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
    ]
