# Generated by Django 4.2.1 on 2023-06-08 15:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_alter_post_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('танк', 'Танк'), ('хил', 'Хил'), ('дд', 'ДД'), ('торговец', 'Торговец'), ('гильдмастер', 'Гильдмастер'), ('квестгивер', 'Квестгивер'), ('кузнец', 'Кузнец'), ('кожевник', 'Кожевник'), ('зельевар', 'Зельевар'), ('мастер заклинаний', 'Мастер заклинаней')], default='торговец', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст объявления'),
        ),
    ]
